export PATH="/data/stsutsui/public/word-learning.cogsci2020/miniconda/bin:$PATH"
which python

python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 1 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 2 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 3 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 4 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 5 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 6 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 7 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 8 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 9 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-1100-parent.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_parent.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_0.60.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_scattered_0.60.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_looked_0.60.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_concentrated_not-looked_0.60.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_0.06.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_0.06.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_concentrated_1.00.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_small_scattered_1.00.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_scattered_1.00.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_large_concentrated_1.00.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-50-parent.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-800-parent.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-100-parent.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-200-parent.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-400-parent.txt --seed 10 --gpu 1
python main.py --saveroot ../experiments/cogsci2020/ --train  ../data/dataset_txt/naiming_3s_whole_img_acuity_num-600-parent.txt --seed 10 --gpu 1